/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import com.mycompany.banco.Agencia;
import javax.swing.JOptionPane;
/**
 *
 * @author Alunos
 */
public class Agencias extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Agencias() {
        initComponents();
    }
    
    Agencia agencia_jframe = new Agencia();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nomeAgencia = new javax.swing.JLabel();
        lbl_endereco = new javax.swing.JLabel();
        txtField_nomeAgencia = new javax.swing.JTextField();
        txtField_endereco = new javax.swing.JTextField();
        txtField_numero = new javax.swing.JTextField();
        btn_Gravar = new javax.swing.JButton();
        btn_Ler = new javax.swing.JButton();
        txtField_complemento = new javax.swing.JTextField();
        txtField_bairro = new javax.swing.JTextField();
        txtField_cidade = new javax.swing.JTextField();
        txtField_cep = new javax.swing.JTextField();
        txtField_cnpj = new javax.swing.JTextField();
        txtField_gerente = new javax.swing.JTextField();
        btn_Limpar = new javax.swing.JButton();
        lbl_numero = new javax.swing.JLabel();
        lbl_complemento = new javax.swing.JLabel();
        lbl_bairro = new javax.swing.JLabel();
        lbl_cidade = new javax.swing.JLabel();
        lbl_cep = new javax.swing.JLabel();
        lbl_cnpj = new javax.swing.JLabel();
        lbl_gerente = new javax.swing.JLabel();
        combo_uf = new javax.swing.JComboBox<>();
        lbl_gerente1 = new javax.swing.JLabel();
        lbl_nomeAgencia1 = new javax.swing.JLabel();
        txtField_nomeAgencia1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        lbl_nomeAgencia.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nomeAgencia.setText("Nome da Agência");

        lbl_endereco.setForeground(new java.awt.Color(0, 0, 0));
        lbl_endereco.setText("Endereço da Agência");

        txtField_nomeAgencia.setBackground(new java.awt.Color(204, 204, 204));
        txtField_nomeAgencia.setForeground(new java.awt.Color(51, 51, 51));
        txtField_nomeAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_nomeAgenciaActionPerformed(evt);
            }
        });

        txtField_endereco.setBackground(new java.awt.Color(204, 204, 204));
        txtField_endereco.setForeground(new java.awt.Color(51, 51, 51));

        txtField_numero.setBackground(new java.awt.Color(204, 204, 204));
        txtField_numero.setForeground(new java.awt.Color(51, 51, 51));
        txtField_numero.setToolTipText("");

        btn_Gravar.setText("Gravar");
        btn_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GravarActionPerformed(evt);
            }
        });

        btn_Ler.setText("Ler");
        btn_Ler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LerActionPerformed(evt);
            }
        });

        txtField_complemento.setBackground(new java.awt.Color(204, 204, 204));
        txtField_complemento.setForeground(new java.awt.Color(51, 51, 51));
        txtField_complemento.setToolTipText("");

        txtField_bairro.setBackground(new java.awt.Color(204, 204, 204));
        txtField_bairro.setForeground(new java.awt.Color(51, 51, 51));
        txtField_bairro.setToolTipText("");

        txtField_cidade.setBackground(new java.awt.Color(204, 204, 204));
        txtField_cidade.setForeground(new java.awt.Color(51, 51, 51));
        txtField_cidade.setToolTipText("");

        txtField_cep.setBackground(new java.awt.Color(204, 204, 204));
        txtField_cep.setForeground(new java.awt.Color(51, 51, 51));
        txtField_cep.setToolTipText("");

        txtField_cnpj.setBackground(new java.awt.Color(204, 204, 204));
        txtField_cnpj.setForeground(new java.awt.Color(51, 51, 51));
        txtField_cnpj.setToolTipText("");

        txtField_gerente.setBackground(new java.awt.Color(204, 204, 204));
        txtField_gerente.setForeground(new java.awt.Color(51, 51, 51));
        txtField_gerente.setToolTipText("");

        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        lbl_numero.setForeground(new java.awt.Color(0, 0, 0));
        lbl_numero.setText("Número da Agência");

        lbl_complemento.setForeground(new java.awt.Color(0, 0, 0));
        lbl_complemento.setText("Complemento da Agência");

        lbl_bairro.setForeground(new java.awt.Color(0, 0, 0));
        lbl_bairro.setText("Bairro da Agência");

        lbl_cidade.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cidade.setText("Cidade da Agência");

        lbl_cep.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cep.setText("CEP da Agência");

        lbl_cnpj.setForeground(new java.awt.Color(0, 0, 0));
        lbl_cnpj.setText("CNPJ da Agência");

        lbl_gerente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_gerente.setText("Gerente da Agência");

        combo_uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        combo_uf.setToolTipText("");
        combo_uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_ufActionPerformed(evt);
            }
        });

        lbl_gerente1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_gerente1.setText("Estado da Agência");

        lbl_nomeAgencia1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nomeAgencia1.setText("Id da Agência");

        txtField_nomeAgencia1.setBackground(new java.awt.Color(204, 204, 204));
        txtField_nomeAgencia1.setForeground(new java.awt.Color(51, 51, 51));
        txtField_nomeAgencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_nomeAgencia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nomeAgencia1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Gravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(btn_Limpar)
                        .addGap(107, 107, 107)
                        .addComponent(btn_Ler)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_bairro)
                            .addComponent(lbl_nomeAgencia)
                            .addComponent(lbl_endereco)
                            .addComponent(lbl_numero)
                            .addComponent(lbl_complemento)
                            .addComponent(lbl_cidade)
                            .addComponent(lbl_cep)
                            .addComponent(lbl_cnpj)
                            .addComponent(lbl_gerente)
                            .addComponent(lbl_gerente1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtField_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_endereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_nomeAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtField_nomeAgencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeAgencia1)
                    .addComponent(txtField_nomeAgencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeAgencia)
                    .addComponent(txtField_nomeAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_endereco)
                    .addComponent(txtField_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_numero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_complemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cnpj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField_gerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_gerente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gerente1)
                    .addComponent(combo_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Gravar)
                    .addComponent(btn_Limpar)
                    .addComponent(btn_Ler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtField_nomeAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_nomeAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_nomeAgenciaActionPerformed

    private void btn_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GravarActionPerformed
        agencia_jframe.setNome(txtField_nomeAgencia.getText());
        agencia_jframe.setEndereco(txtField_endereco.getText());
        agencia_jframe.setNumero(txtField_numero.getText());
        agencia_jframe.setComplemento(txtField_complemento.getText());
        agencia_jframe.setBairro(txtField_bairro.getText());
        agencia_jframe.setCidade(txtField_cidade.getText());
        agencia_jframe.setCep(txtField_cep.getText());
        agencia_jframe.setCnpj(txtField_cnpj.getText());
        agencia_jframe.setGerente(txtField_gerente.getText());
        agencia_jframe.setUf(combo_uf.getSelectedItem().toString());
        btn_LimparActionPerformed(evt);
    }//GEN-LAST:event_btn_GravarActionPerformed

    private void btn_LerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LerActionPerformed
        txtField_nomeAgencia.setText(agencia_jframe.getNome()); 
        txtField_endereco.setText(agencia_jframe.getEndereco()); 
        txtField_numero.setText(agencia_jframe.getNumero());
        txtField_complemento.setText(agencia_jframe.getComplemento()); 
        txtField_bairro.setText(agencia_jframe.getBairro()); 
        txtField_cidade.setText(agencia_jframe.getCidade()); 
        txtField_cep.setText(agencia_jframe.getCep()); 
        txtField_cnpj.setText(agencia_jframe.getCnpj()); 
        txtField_gerente.setText(agencia_jframe.getGerente()); 
        combo_uf.setSelectedItem(agencia_jframe.getUf());
    }//GEN-LAST:event_btn_LerActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
       txtField_nomeAgencia.setText(""); 
        txtField_endereco.setText(""); 
        txtField_numero.setText("");
        txtField_complemento.setText(""); 
        txtField_bairro.setText(""); 
        txtField_cidade.setText(""); 
        txtField_cep.setText(""); 
        txtField_cnpj.setText(""); 
        txtField_gerente.setText(""); 
        combo_uf.setSelectedIndex(0);
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void combo_ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ufActionPerformed

    private void txtField_nomeAgencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_nomeAgencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_nomeAgencia1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Gravar;
    private javax.swing.JButton btn_Ler;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JComboBox<String> combo_uf;
    private javax.swing.JLabel lbl_bairro;
    private javax.swing.JLabel lbl_cep;
    private javax.swing.JLabel lbl_cidade;
    private javax.swing.JLabel lbl_cnpj;
    private javax.swing.JLabel lbl_complemento;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_gerente;
    private javax.swing.JLabel lbl_gerente1;
    private javax.swing.JLabel lbl_nomeAgencia;
    private javax.swing.JLabel lbl_nomeAgencia1;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JTextField txtField_bairro;
    private javax.swing.JTextField txtField_cep;
    private javax.swing.JTextField txtField_cidade;
    private javax.swing.JTextField txtField_cnpj;
    private javax.swing.JTextField txtField_complemento;
    private javax.swing.JTextField txtField_endereco;
    private javax.swing.JTextField txtField_gerente;
    private javax.swing.JTextField txtField_nomeAgencia;
    private javax.swing.JTextField txtField_nomeAgencia1;
    private javax.swing.JTextField txtField_numero;
    // End of variables declaration//GEN-END:variables
}
