/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import com.mycompany.banco.Cliente;
import javax.swing.JOptionPane;
/**
 *
 * @author Alunos
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }
    
    Cliente c = new Cliente();
    char sexoSelecionado = ' ';
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Cliente = new javax.swing.JLabel();
        lbl_Endereco = new javax.swing.JLabel();
        lbl_Numero = new javax.swing.JLabel();
        textField_Cliente = new javax.swing.JTextField();
        textField_Endereco = new javax.swing.JTextField();
        textField_Numero = new javax.swing.JTextField();
        btn_Gravar = new javax.swing.JButton();
        btn_Ler = new javax.swing.JButton();
        lbl_Bairro = new javax.swing.JLabel();
        txtField_Bairro = new javax.swing.JTextField();
        txtField_Cidade = new javax.swing.JTextField();
        lbl_Cidade = new javax.swing.JLabel();
        txtField_Cep = new javax.swing.JTextField();
        lbl_Cep = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        txtField_Email = new javax.swing.JTextField();
        lbl_Telefone = new javax.swing.JLabel();
        txtField_Telefone = new javax.swing.JTextField();
        lbl_Cpf_Cnpj = new javax.swing.JLabel();
        txtField_Cpf_Cpnj = new javax.swing.JTextField();
        btn_Limpar = new javax.swing.JButton();
        lbl_sexo = new javax.swing.JLabel();
        lbl_uf = new javax.swing.JLabel();
        combo_estado = new javax.swing.JComboBox<>();
        radio_sexo_f = new javax.swing.JRadioButton();
        radio_sexo_m = new javax.swing.JRadioButton();
        lbl_IdCliente = new javax.swing.JLabel();
        txtField_Id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        lbl_Cliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Cliente.setText("Nome do Cliente");

        lbl_Endereco.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Endereco.setText("Endereço do Cliente");

        lbl_Numero.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Numero.setText("Número");

        textField_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        textField_Cliente.setForeground(new java.awt.Color(51, 51, 51));

        textField_Endereco.setBackground(new java.awt.Color(204, 204, 204));
        textField_Endereco.setForeground(new java.awt.Color(51, 51, 51));

        textField_Numero.setBackground(new java.awt.Color(204, 204, 204));
        textField_Numero.setForeground(new java.awt.Color(51, 51, 51));
        textField_Numero.setToolTipText("");

        btn_Gravar.setText("Gravar");
        btn_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GravarActionPerformed(evt);
            }
        });

        btn_Ler.setText("Ler");
        btn_Ler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LerActionPerformed(evt);
            }
        });

        lbl_Bairro.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Bairro.setText("Bairro");

        txtField_Bairro.setBackground(new java.awt.Color(204, 204, 204));
        txtField_Bairro.setForeground(new java.awt.Color(51, 51, 51));
        txtField_Bairro.setToolTipText("");

        txtField_Cidade.setBackground(new java.awt.Color(204, 204, 204));
        txtField_Cidade.setForeground(new java.awt.Color(51, 51, 51));
        txtField_Cidade.setToolTipText("");

        lbl_Cidade.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Cidade.setText("Cidade");

        txtField_Cep.setBackground(new java.awt.Color(204, 204, 204));
        txtField_Cep.setForeground(new java.awt.Color(51, 51, 51));
        txtField_Cep.setToolTipText("");

        lbl_Cep.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Cep.setText("CEP");

        lbl_Email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Email.setText("Email");

        txtField_Email.setBackground(new java.awt.Color(204, 204, 204));
        txtField_Email.setForeground(new java.awt.Color(51, 51, 51));
        txtField_Email.setToolTipText("");

        lbl_Telefone.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Telefone.setText("Telefone");

        txtField_Telefone.setBackground(new java.awt.Color(204, 204, 204));
        txtField_Telefone.setForeground(new java.awt.Color(51, 51, 51));
        txtField_Telefone.setToolTipText("");

        lbl_Cpf_Cnpj.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Cpf_Cnpj.setText("CPF/CNPJ");

        txtField_Cpf_Cpnj.setBackground(new java.awt.Color(204, 204, 204));
        txtField_Cpf_Cpnj.setForeground(new java.awt.Color(51, 51, 51));
        txtField_Cpf_Cpnj.setToolTipText("");

        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        lbl_sexo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_sexo.setText("Sexo");

        lbl_uf.setForeground(new java.awt.Color(0, 0, 0));
        lbl_uf.setText("Estado do Cliente");

        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        radio_sexo_f.setText("F");
        radio_sexo_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_sexo_fActionPerformed(evt);
            }
        });

        radio_sexo_m.setText("M");
        radio_sexo_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_sexo_mActionPerformed(evt);
            }
        });

        lbl_IdCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_IdCliente.setText("Id do Cliente");

        txtField_Id.setBackground(new java.awt.Color(204, 204, 204));
        txtField_Id.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lbl_sexo)
                        .addGap(86, 86, 86)
                        .addComponent(radio_sexo_f)
                        .addGap(6, 6, 6)
                        .addComponent(radio_sexo_m))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lbl_uf)
                        .addGap(18, 18, 18)
                        .addComponent(combo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Cpf_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtField_Cpf_Cpnj, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_Gravar)
                        .addGap(154, 154, 154)
                        .addComponent(btn_Limpar)
                        .addGap(137, 137, 137)
                        .addComponent(btn_Ler)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_IdCliente))
                    .addComponent(txtField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lbl_sexo))
                            .addComponent(radio_sexo_f)
                            .addComponent(radio_sexo_m)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_Cliente)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Endereco)
                            .addComponent(lbl_uf))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_Numero))
                    .addComponent(textField_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_Bairro))
                    .addComponent(txtField_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_Cidade))
                    .addComponent(txtField_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_Cep))
                    .addComponent(txtField_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_Email))
                    .addComponent(txtField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_Telefone))
                    .addComponent(txtField_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_Cpf_Cnpj))
                    .addComponent(txtField_Cpf_Cpnj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Gravar)
                    .addComponent(btn_Limpar)
                    .addComponent(btn_Ler)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GravarActionPerformed
        //Gravar os dados no objeto cliente c
        //Falta CPF/CNPJ
        c.setNome(textField_Cliente.getText());
        c.setEndereco(textField_Endereco.getText());
        c.setNumero(textField_Numero.getText());
        c.setBairro(txtField_Bairro.getText());
        c.setCidade(txtField_Cidade.getText());
        c.setCep(txtField_Cep.getText());
        c.setEmail(txtField_Email.getText());
        c.setTelefone(txtField_Telefone.getText());
        c.setUf(combo_estado.getSelectedItem().toString());
        c.setSexo(sexoSelecionado);
        JOptionPane.showMessageDialog(null, "Parabens, você se cadastrou ");
        btn_LimparActionPerformed(evt);
    }//GEN-LAST:event_btn_GravarActionPerformed

    private void btn_LerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LerActionPerformed
        textField_Cliente.setText(c.getNome());
        textField_Endereco.setText(c.getEndereco());
        textField_Numero.setText(c.getNumero());
        txtField_Bairro.setText(c.getBairro());
        txtField_Cidade.setText(c.getCidade());
        txtField_Cep.setText(c.getCep());
        txtField_Telefone.setText(c.getTelefone());
        txtField_Email.setText(c.getEmail());
        combo_estado.setSelectedItem(c.getUf());
        if(c.getSexo() == 'F')
        {
            radio_sexo_f.setSelected(true);
            radio_sexo_m.setSelected(false);
        }
        else if(c.getSexo() == 'M')
        {
            radio_sexo_f.setSelected(false);
            radio_sexo_m.setSelected(true);
        }
    }//GEN-LAST:event_btn_LerActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        textField_Cliente.setText("");
        textField_Endereco.setText("");
        textField_Numero.setText("");
        txtField_Bairro.setText("");
        txtField_Cidade.setText("");
        txtField_Cep.setText("");
        txtField_Telefone.setText("");
        txtField_Email.setText("");
        txtField_Cpf_Cpnj.setText("");
        combo_estado.setSelectedIndex(0);
        radio_sexo_f.setSelected(false);
        radio_sexo_m.setSelected(false);
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void radio_sexo_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_sexo_fActionPerformed
       if(radio_sexo_f.isSelected())
       {
           radio_sexo_m.setSelected(false);
           sexoSelecionado = radio_sexo_f.getText().charAt(0);
       }
    }//GEN-LAST:event_radio_sexo_fActionPerformed

    private void radio_sexo_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_sexo_mActionPerformed
       if(radio_sexo_m.isSelected())
       {
           radio_sexo_f.setSelected(false);
           sexoSelecionado = radio_sexo_m.getText().charAt(0);
       }
    }//GEN-LAST:event_radio_sexo_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Gravar;
    private javax.swing.JButton btn_Ler;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JLabel lbl_Bairro;
    private javax.swing.JLabel lbl_Cep;
    private javax.swing.JLabel lbl_Cidade;
    private javax.swing.JLabel lbl_Cliente;
    private javax.swing.JLabel lbl_Cpf_Cnpj;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Endereco;
    private javax.swing.JLabel lbl_IdCliente;
    private javax.swing.JLabel lbl_Numero;
    private javax.swing.JLabel lbl_Telefone;
    private javax.swing.JLabel lbl_sexo;
    private javax.swing.JLabel lbl_uf;
    private javax.swing.JRadioButton radio_sexo_f;
    private javax.swing.JRadioButton radio_sexo_m;
    private javax.swing.JTextField textField_Cliente;
    private javax.swing.JTextField textField_Endereco;
    private javax.swing.JTextField textField_Numero;
    private javax.swing.JTextField txtField_Bairro;
    private javax.swing.JTextField txtField_Cep;
    private javax.swing.JTextField txtField_Cidade;
    private javax.swing.JTextField txtField_Cpf_Cpnj;
    private javax.swing.JTextField txtField_Email;
    private javax.swing.JTextField txtField_Id;
    private javax.swing.JTextField txtField_Telefone;
    // End of variables declaration//GEN-END:variables
}
